apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/
- ingress.yaml

configMapGenerator:
- name: litellm-config
  behavior: replace
  files:
  - litellm-config.yaml

patches:
 - target:
      group: apps
      version: v1
      kind: Deployment
      name: model-router-litellm
   path: image-patch.yaml

images:
  - name: agentic-layer/model-router-litellm
    newName: agentic-layer/model-router-litellm
    newTag: latest
  - name: ghcr.io/berriai/litellm
    newName: ghcr.io/berriai/litellm
    newTag: main-stable